### ISSUE TITLE
building-a-blog-with-svelte-and-notion

### ISSUE THREAD

**Issue by noahsalvi** [r-bt/r-bt.com#1]
Awesome I love how you use sotion for your site.

I was able to see the changes in your learning blog "building-a-blog-with-svelte-and-notion" in real time :D

Btw I noticed two things with r-bt.com
- You have sotion as a normal dependency and not just as a devDependency. Changing it fixed the SSR Error that I was getting when running your project locally and it should also reduce the size of the bundle that the client gets.
-  learning/index.svelte, is there a reason why you chose to fetch the scope on "onMount" and not in the preload method?

**Comment by r-bt** [comment]
Hahaha, yeah it's really nice to just be writing in Notion and refresh to page to see what I'll look like when done

Opps, yep that should be a `devDepdendecy`. Thanks for pointing that out :)

I initially was fetching the scope in `preload` however since I export the site to host statically on netlify this meant that if people just went to `r-bt.com/learning` it would only show the static content and not re-fetch (i.e. won't show new posts from after export). As well, it exports all the posts as pages (e.g. `__sapper__/export/learning/building-a-blog-with-svelte-and-notion.html`) so if people load that it dosn't load new changes. 

Although thinking about it, I could do both. Preload the content and re-fetch on the client side if user navigated directly to the page. That way I'd get faster load times and it'd update when ready. Something I'll have to look into later :)
